/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stm32f4xx.h>
#include <stdint.h>
#include "GPIOxDriver.h"
#include "BasicTimer.h"

GPIO_Handler_t handlerUserLed = {0};
BasicTimer_Handler_t handlerTimer = {0};

int main(void)
{
	handlerUserLed.pGPIOx = GPIOA;
	handlerUserLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	handlerUserLed.GPIO_PinConfig.GPIO_PinNumber = PIN_5;
	handlerUserLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OTYPE_PUSHPULL;
	handlerUserLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OSPEEDR_FAST;
	handlerUserLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;

	handlerTimer.ptrTIMx = TIM2;
	handlerTimer.TIMx_Config.TIMx_mode = BTIMER_MODE_UP;
	handlerTimer.TIMx_Config.TIMx_speed = BTIMER_SPEED_100us;
	handlerTimer.TIMx_Config.TIMx_period = 1000;
	handlerTimer.TIMx_Config.TIMx_interruptEnable = 1;

	GPIO_Config(&handlerUserLed);
	GPIO_WritePin(&handlerUserLed, SET);
	BasicTimer_Config(&handlerTimer);

    while (1){

    	}
    return 0;
    }

void BasicTimer2_Callback(void){
	GPIOxTooglePin(&handlerUserLed);
}
