/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stm32f4xx.h>
#include <stdint.h>


uint32_t counter = 0;
uint32_t *ptrCounter;
uint32_t auxCounter = 0 ;
uint8_t byteVariable;
uint8_t *ptrByteVariable;

int main(void)
{
	/*Trabajando con la variable de 32 bits*/

	counter = 20000;	//Asignando un valor a la variable

	auxCounter = counter;	//C es pasado por valor.

	//Hacer que el puntero apunte a una variable

	ptrCounter = &counter;

	//Modificar el valor almacenado en la memoria donde apunta

	*ptrCounter = 500000000;

	ptrCounter++;

	*ptrCounter = 500000000;

	byteVariable = 32;
	ptrByteVariable = &byteVariable;
	*ptrByteVariable = 200;

//Intentando mezclar punteros

	auxCounter = (uint32_t)&counter; //Haciendo un cast para obtener el valor
	ptrByteVariable = (uint8_t *)auxCounter;
	*ptrByteVariable = 1;


    while (1){

    }
}
